--inserciones
INSERT INTO CARRERA(CODIGO,NOMBRE,FECHA_CREACION,NUM_RESOLUCION,DURACION,ES_ACREDITADA,ESTADO)
VALUES(seq_carrera.nextval,'TECNICO SUPERIOR EN ELECTRONICA','20/12/2016','001-00-2016',4,'N','A');

INSERT INTO CARRERA(CODIGO,NOMBRE,FECHA_CREACION,NUM_RESOLUCION,DURACION,ES_ACREDITADA,ESTADO)
VALUES(seq_carrera.nextval, 'PROGRAMACION DE COMPUTADORAS','03/09/2012','033-22-2012',4,'S','A');

INSERT INTO CARRERA(CODIGO,NOMBRE,FECHA_CREACION,NUM_RESOLUCION,DURACION,ES_ACREDITADA,ESTADO)
VALUES(seq_carrera.nextval,'TECNICO SUPERIOR EN ELECTRICIDAD','15/12/2017','001-00-2016',4,'N','A');

/*INSERT INTO CARRERA(NOMBRE,FECHA_CREACION,NUM_RESOLUCION,DURACION,ES_ACREDITADA,ESTADO)
VALUES('ING. EN INFORMATICA','20/04/2018','011-03-2014',8,'S','A');*/

---MATERIAS DE LA CARRERA TSE
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'CALCULO I');
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'GEOMETRIA ANALITICA Y VECTORES');
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'ALGEBRA ');
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'FISICA MECANICA ');
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'DIBUJO I');
--SEMESTRE I TSE
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (1,1,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (2,1,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (3,1,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (4,1,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (5,1,1,20000);

---MATERIAS DE LA CARRERA TSE
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'CALCULO II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'FISICA ELECTRICIDAD');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'FISICA ONDAS');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'DIBUJO II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'QUIMICA');

--SEMESTRE II TSE
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (6,1,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (7,1,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (8,1,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (9,1,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (10,1,2,20000);


---MATERIAS DE LA CARRERA TSE
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'CALCULO III');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ELECTRONICA I');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'SISTEMAS DIGITALES');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'MECANICA CLASICA');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'MICROPROCESADOR I');

--SEMESTRE III TSE
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (11,1,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (12,1,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (13,1,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (14,1,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (15,1,3,20000);


---MATERIAS DE LA CARRERA TSE
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval,'ELECTROMAGNETISMO');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval,'ELECTRONICA APLICADA');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval,'TALLER');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval,'PROGRAMACION');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval,'MICROPROCESADOR II');

--SEMESTRE IV TSE
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (16,1,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (17,1,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (18,1,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (19,1,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (20,1,4,20000);

--ALUMNOS DE TSE

INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'4652321','SAMUEL',NULL,'SOSA','PEREIRA','01/05/1995','021523124','AVIADORES Y ESPAÑA',NULL,'A');
INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'3745658','ANA','LAURA','GOMEZ','SOLIS','05/07/1994','0985632142','CHILE Y OLIVA','ANALIA@GMAIL.COM','A');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(1,1,'25/01/2017',NULL,'C');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(2,1,'22/01/2018',NULL,'C');

--MATRICULACION DE LOS ALUMNOS DEL TSE

-- ALUMNO 1 SEMESTRE 1  TSE
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,1,2017,1,'02/02/2017',3,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,2,2017,1,'02/02/2017',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,3,2017,1,'03/02/2017',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,4,2017,1,'03/02/2017',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,5,2017,1,'04/02/2017',0,'A');

-- ALUMNO 1 SEMESTRE 2  TSE
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,6,2017,2,'02/07/2017',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,7,2017,2,'02/07/2017',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,8,2017,2,'03/07/2017',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,10,2017,2,'03/07/2017',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,5,2017,2,'03/07/2017',3,'C');

-- ALUMNO 1 SEMESTRE 3  TSE
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,9,2018,1,'01/02/2018',1,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,11,2018,1,'02/02/2018',3,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,12,2018,1,'02/02/2018',3,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,13,2018,1,'02/02/2018',3,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,14,2018,1,'05/02/2018',4,'C');

--ALUMNO 1 SEMESTRE 4 TSE

INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,9,2018,2,'01/07/2018',0,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,16,2018,2,'02/07/2018',0,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,17,2018,2,'02/07/2018',0,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,18,2018,2,'02/07/2018',0,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,19,2018,2,'05/07/2018',0,'C');


-- ALUMNO 2 SEMESTRE 1  TSE
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,1,2018,1,'02/02/2018',1,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,2,2018,1,'02/02/2018',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,3,2018,1,'03/02/2018',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,4,2018,1,'03/02/2018',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,5,2018,1,'04/02/2018',1,'C');

-- ALUMNO 2 SEMESTRE 2  TSE
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,1,2018,2,'02/07/2018',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,5,2018,2,'02/07/2018',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,8,2018,2,'03/07/2018',0,'X');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(2,10,2018,2,'03/07/2018',0,'X');


-------------------------------------------------------------------------------------------------
---MATERIAS DE LA CARRERA PC
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'ALGORTIMICA I');
--INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'GEOMETRIA ANALITICA Y VECTORES');
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'LOGICA MATEMATICA');
INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'INFORMATICA');
--INSERT INTO MATERIA (CODIGO, NOMBRE) VALUES(seq_materia.nextval, 'FISICA ELECTRICIDAD');
--SEMESTRE I PC
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (21,2,1,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (2,2,1,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (22,2,1,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (23,2,1,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (7,2,1,25000);

---MATERIAS DE LA CARRERA PC
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ALGORIMITCA II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'CALCULO INTEGRAL');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ESTRUCTURA DE DATOS');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'REDES I');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'E-COMMERCE');

--SEMESTRE II  PC
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (24,2,2,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (25,2,2,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (26,2,2,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (27,2,2,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (28,2,2,25000);

---MATERIAS DE LA CARRERA PC
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'BASE DE DATOS I');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'REDES II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'COMPILADORES');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'PROGRAMACION WEB I');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'CALCULO VECTORIAL');

--SEMESTRE III PC
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (29,2,3,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (30,2,3,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (31,2,3,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (32,2,3,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (33,2,3,25000);

---MATERIAS DE LA CARRERA PC
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'BASE DE DATOS II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'PROGRAMACION WEB II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'PROGRAMACION MOBILE');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ING. DE SOFTWARE');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'TALLER DE PROGRAMACION');

--SEMESTRE IV PC
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (34,2,4,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (35,2,4,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (36,2,4,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (37,2,4,25000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (38,2,4,25000);

--ALUMNOS DE PC

INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'3582745','INGRID',NULL,'MOLINAS','NULL','11/05/1993','0971521478','CHILE Y MANDUVIRA',NULL,'I');


INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(3,2,'22/01/2013','26/12/2014','T');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(1,3,'20/01/2018',NULL,'C');

--MATRICULACION DE LOS ALUMNOS DEL PC

-- ALUMNO 3 SEMESTRE 1  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,21,2013,1,'02/02/2013',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,2,2013,1,'02/02/2013',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,22,2013,1,'03/02/2013',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,23,2013,1,'03/02/2013',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,7,2013,1,'04/02/2013',4,'C');

-- ALUMNO 3 SEMESTRE 2  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,24,2013,2,'02/07/2013',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,25,2013,2,'02/07/2013',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,26,2013,2,'03/07/2013',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,27,2013,2,'03/07/2013',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,28,2013,2,'04/07/2013',5,'C');

-- ALUMNO 3 SEMESTRE 3  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,29,2014,1,'02/02/2014',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,30,2014,1,'02/02/2014',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,31,2014,1,'03/02/2014',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,32,2014,1,'03/02/2014',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,33,2014,1,'04/02/2014',4,'C');

--ALUMNO 3 SEMESTRE 4 TSE

INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,34,2014,2,'02/07/2014',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,35,2014,2,'02/07/2014',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,36,2014,2,'03/07/2014',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,37,2014,2,'03/07/2014',5,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(3,38,2014,2,'04/07/2014',3,'C');


-- ALUMNO 1 SEMESTRE 1  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,21,2018,1,'02/02/2018',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,2,2018,1,'02/02/2018',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,22,2018,1,'03/02/2018',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,23,2018,1,'03/02/2018',1,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,7,2018,1,'04/02/2018',4,'C');

-- ALUMNO 1 SEMESTRE 2  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,24,2018,2,'02/07/2018',0,'X');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,25,2018,2,'02/07/2018',0,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,28,2018,2,'03/07/2018',0,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(1,23,2018,2,'03/07/2018',0,'C');


--MATERIAS DE LA CARRERA TSEL
--INSERT INTO MATERIA (NOMBRE) VALUES('CALCULO I');
--INSERT INTO MATERIA (NOMBRE) VALUES('GEOMETRIA ANALITICA Y VECTORES');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'FISICA I');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'EMPRENDEDORISMO');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'DISEÑO ASISTIDO POR COMPUTADORA');
--SEMESTRE I TSEL
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (1,3,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (2,3,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (39,3,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (40,3,1,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (41,3,1,20000);

--INSERT INTO MATERIA (NOMBRE) VALUES('CALCULO II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'FISICA II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ELECTROTECNIA I');
--INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'CALCULO III');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'TERMODINAMICA');
--SEMESTRE II TSEL
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (6,3,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (42,3,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (43,3,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (11,3,2,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (44,3,2,20000);

INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ELECTROTECNICA II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'INSTALACIONES ELECTRICAS I');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'LABORATORIO DE ELECTROTECNIA');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'PREVENSION Y SEGURIDAD');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'MECANICA DE FLUIDOS');
--SEMESTRE III TSEL
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (45,3,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (46,3,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (47,3,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (48,3,3,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (49,3,3,20000);

INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'INSTALACIONES ELECTRICAS II');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'CIRCUITOS ELECTRICOS');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ELECTRONICA BASICA');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ELECTRICIDAD INDUSTRIAL');
INSERT INTO MATERIA (CODIGO,NOMBRE) VALUES(seq_materia.nextval, 'ELECTRICIDAD DE POTENCIA');
--SEMESTRE IV TSEL
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (50,3,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (51,3,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (52,3,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (53,3,4,20000);
INSERT INTO CARRERA_MATERIA(COD_MATERIA,COD_CARRERA,SEMESTRE,COSTO) VALUES (54,3,4,20000);

INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'4215874','JIMENA','JAZMIN','PEREZ','SANDOVAL','11/12/1993','021526321','LAS PERLAS Y SARAVI',NULL,'I');

INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'5369741','CARLOS','ALBERTO','BENITEZ',NULL,'09/09/1995','0985362415','LAS PERLAS Y SARAVI','CARLOSAL@HOTMAIL.COM','A');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(4,3,'25/01/2018',NULL,'A');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(5,3,'25/01/2018',NULL,'C');

--MATRICULACION DE LOS ALUMNOS DEL TSEL

-- ALUMNO 4 SEMESTRE 1  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(4,1,2018,1,'02/02/2018',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(4,2,2018,1,'02/02/2018',1,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(4,39,2018,1,'03/02/2018',1,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(4,40,2018,1,'03/02/2018',0,'A');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(4,41,2018,1,'04/02/2018',0,'A');

-- ALUMNO 5 SEMESTRE 1  PC
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(5,1,2018,1,'02/02/2018',4,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(5,2,2018,1,'03/02/2018',3,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(5,39,2018,1,'03/02/2018',3,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(5,40,2018,1,'03/02/2018',2,'C');
INSERT INTO MATRICULACION(COD_ALUMNO,COD_MATERIA,ANHO,NUM_SEMESTRE,FECHA_MATRIC,CALIFICACION,SITUACION)
VALUES(5,41,2018,1,'03/02/2018',0,'X');


INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'5532741','JOSE','RAUL','BAEZ','ROA','01/08/1996','0991325741','ESPAÑA Y SACRAMENTO','JOSEBA96@GMAIL.COM','A');

INSERT INTO ALUMNO (CODIGO,CI,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,FECHA_NACIMIENTO,TELEFONO,DIRECCION,EMAIL,ESTADO)
VALUES(seq_alumno.nextval,'5369781','JOHANA',NULL,'PEREZ','RIVEROS','09/07/1994','0994325641','SAN MARTIN Y ANDRADE','JOHANARIV@HOTMAIL.COM','A');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(6,1,'30/06/2018',NULL,'C');

INSERT INTO ALUMNO_CARRERA(COD_ALUMNO,COD_CARRERA,FECHA_INGRESO,FECHA_EGRESO,ESTADO)
VALUES(7,2,'30/06/2018',NULL,'C');

